using System.Windows;
using CommunityToolkit.Mvvm.ComponentModel;

namespace SmartAlloc.Services;

public class LocalizationProxy : ObservableObject
{
    public static LocalizationProxy Instance { get; } = new();
    public string this[string key] => LocalizationService.Current.Get(key);

    public LocalizationProxy()
    {
        LocalizationService.Current.LanguageChanged += () =>
            OnPropertyChanged(string.Empty);
    }
}

public class LocalizationService
{
    private static LocalizationService? _current;
    public static LocalizationService Current => _current ??= new LocalizationService();

    public static readonly List<LanguageOption> AvailableLanguages =
    [
        new("en", "English"),
        new("pl", "Polski"),
        new("de", "Deutsch"),
        new("es", "Español"),
        new("fr", "Français"),
        new("pt", "Português"),
        new("ru", "Русский"),
        new("zh", "中文"),
        new("ja", "日本語"),
        new("ar", "العربية"),
        new("hi", "हिन्दी")
    ];

    private string _currentLanguage = "en";
    public string CurrentLanguage => _currentLanguage;

    public event Action? LanguageChanged;

    private static readonly Dictionary<string, Dictionary<string, string>> Translations = new()
    {
        ["en"] = new()
        {
            ["Nav.Dashboard"] = "Dashboard",
            ["Nav.Transactions"] = "Transactions",
            ["Nav.Budgets"] = "Budgets",
            ["Nav.Goals"] = "Goals",
            ["Nav.Statistics"] = "Statistics",
            ["Nav.Calendar"] = "Calendar",
            ["Nav.PdfReport"] = "PDF Report",
            ["Nav.Settings"] = "Settings",
            ["Nav.LogOut"] = "Log Out",
            ["Nav.Menu"] = "MENU",
            ["Title.Dashboard"] = "Dashboard",
            ["Title.DashboardSub"] = "Your financial overview",
            ["Title.Transactions"] = "Transactions",
            ["Title.TransactionsSub"] = "Manage your income and expenses",
            ["Title.Budgets"] = "Budgets",
            ["Title.BudgetsSub"] = "Control your monthly spending limits",
            ["Title.Goals"] = "Savings Goals",
            ["Title.GoalsSub"] = "Track progress and predict goal achievement date",
            ["Title.Statistics"] = "Statistics",
            ["Title.StatisticsSub"] = "Analyze your spending trends",
            ["Title.Calendar"] = "Payment Calendar",
            ["Title.CalendarSub"] = "View and set reminders for recurring payments",
            ["Title.Settings"] = "Settings",
            ["Title.SettingsSub"] = "Security and configuration",
            ["Label.Balance"] = "Balance",
            ["Label.Income"] = "Income",
            ["Label.Expenses"] = "Expenses",
            ["Label.Savings"] = "Savings",
            ["Label.Amount"] = "Amount",
            ["Label.Date"] = "Date",
            ["Label.Category"] = "Category",
            ["Label.Note"] = "Note",
            ["Label.Type"] = "Type",
            ["Label.Colour"] = "Colour",
            ["Label.Search"] = "Search",
            ["Label.Period"] = "Period",
            ["Label.Remaining"] = "Remaining: ",
            ["Label.Description"] = "Description (optional)",
            ["Label.GoalName"] = "Goal name",
            ["Label.Icon"] = "Icon",
            ["Label.Language"] = "Language",
            ["Btn.AddTransaction"] = "Add transaction",
            ["Btn.SaveBudget"] = "Save budget",
            ["Btn.CreateGoal"] = "✅ Create goal",
            ["Btn.Deposit"] = "💰 Deposit",
            ["Btn.Delete"] = "Delete",
            ["Btn.Save"] = "Save",
            ["Btn.Cancel"] = "Cancel",
            ["Btn.SaveNewPin"] = "Save New PIN",
            ["Btn.ExportBackup"] = "📤  Export Backup",
            ["Btn.ImportBackup"] = "📥  Import Backup",
            ["Btn.DeleteAccount"] = "Delete My Account",
            ["Btn.SaveRecurring"] = "🔁 Save Recurring",
            ["Btn.AddQuickTx"] = "➕ Add Transaction",
            ["Section.NewBudget"] = "➕ New budget:",
            ["Section.NewGoal"] = "🎯 New savings goal",
            ["Section.NewTx"] = "➕ New transaction",
            ["Section.Filters"] = "🔍 Filters",
            ["Section.ChangePin"] = "Change PIN",
            ["Section.AutoLock"] = "Auto-lock",
            ["Section.Backup"] = "Backup & Restore",
            ["Section.Shortcuts"] = "Keyboard Shortcuts",
            ["Section.DangerZone"] = "Danger Zone",
            ["Section.Reminders"] = "🔔 Reminders",
            ["Section.AllRecurring"] = "ALL RECURRING PAYMENTS",
            ["Section.AddRecurring"] = "🔁 Add Recurring Payment",
            ["Tx.Expense"] = "Expense",
            ["Tx.Income"] = "Income",
            ["Pin.CurrentPin"] = "Current PIN",
            ["Pin.NewPin"] = "New PIN",
            ["Pin.ConfirmPin"] = "Confirm New PIN",
            ["Settings.AutoLockDesc"] = "Lock the screen after a period of inactivity.",
            ["Settings.BackupDesc"] = "Export Backup saves an encrypted copy of your database. Import Backup restores all data from a previous backup (current data will be replaced).",
            ["Settings.DangerDesc"] = "Permanently delete your account and all associated data (transactions, budgets, goals, recurring transactions). This action cannot be undone.",
            ["App.Title"] = "SmartAlloc",
            ["App.Subtitle"] = "Finance Planner",
            ["App.Version"] = "SmartAlloc v1.0",
            ["App.Encryption"] = "Data encrypted AES-256",
            ["Theme.Light"] = "Light mode",
            ["Theme.Dark"] = "Dark mode",
            ["Calendar.RemindMe"] = "Remind me",
            ["Calendar.SaveReminder"] = "💾 Save reminder",
            ["Calendar.ClickDay"] = "Click a day with a payment to configure its reminder.",
            ["Calendar.NameCategory"] = "Name / Category",
            ["Calendar.DayOfMonth"] = "Day of month (1–28)",
            ["WhatIf.Prefix"] = "🔮 What-if: extra savings +",
            ["WhatIf.PerMonth"] = "/month",
            ["Label.DisplayCurrency"] = "Display Currency",
            ["Label.DisplayCurrencyHint"] = "Global currency is also in the sidebar.",
            ["Btn.RefreshRates"] = "🔄 Refresh rates",
            ["Section.ExpenseBreakdown"] = "Expense breakdown",
            ["Label.CurrentMonth"] = "Current month  ·  ",
            ["Section.BalanceHistory"] = "Balance history",
            ["Label.Last6Months"] = "Last 6 months",
            ["Section.TransactionList"] = "📋 Transaction list",
            ["Btn.DeleteSelected"] = "🗑 Delete selected",
            ["Label.DayRange"] = "Day (1-28)",
            ["Btn.Add"] = "Add",
            ["Section.RecurringTx"] = "🔁 Recurring transactions",
            ["Tx.ExpenseRadio"] = "📉 Expense",
            ["Tx.IncomeRadio"] = "📈 Income",
            ["Label.TargetAmount"] = "Target Amount",
            ["Label.InitialAmount"] = "Initial Amount",
            ["Btn.Back"] = "← Back",
            ["Label.InsufficientData"] = "ℹ️ Insufficient data",
            ["Label.NoGoals"] = "No goals",
            ["Label.GoalCount"] = "goal(s)",
            ["Title.AdvancedStats"] = "Advanced Statistics",
            ["Title.AdvancedStatsSub"] = "Detailed analysis of your spending and income patterns",
            ["Label.AvgDailyExpense"] = "📉 Avg Daily Expense",
            ["Label.AvgDailyIncome"] = "📈 Avg Daily Income",
            ["Label.SavingsRate"] = "💾 Savings Rate",
            ["Label.BiggestExpense"] = "🔥 Biggest Expense",
            ["Section.TopExpense"] = "🏆 Top Expense Categories (this month)",
            ["Section.IncomeVsExpense"] = "📊 Income vs Expenses (6 months)",
            ["Section.ExpenseTrend"] = "📈 Expense Trend (12 months)",
            ["Section.LanguageDesc"] = "Select the interface language. The app will update immediately.",
            ["Shortcut.Title"] = "Keyboard Shortcuts",
            ["Shortcut.F1Hint"] = "  — press F1 anywhere to open the overlay",
            ["Shortcut.CloseHint"] = "  — press F1 or Esc to close",
            ["Shortcut.Navigation"] = "NAVIGATION",
            ["Shortcut.Actions"] = "ACTIONS",
            ["Shortcut.General"] = "GENERAL",
            ["Shortcut.NavPages"] = "Dashboard, Transactions, Budgets, Goals, Statistics, Settings",
            ["Shortcut.NewTx"] = "New Transaction (go to Transactions)",
            ["Shortcut.GenPdf"] = "Generate PDF Report",
            ["Shortcut.ToggleTheme"] = "Toggle Light / Dark theme",
            ["Shortcut.LockScreen"] = "Lock screen now",
            ["Shortcut.Minimize"] = "Minimize window",
            ["Shortcut.ToggleOverlay"] = "Show / hide keyboard shortcuts overlay",
            ["Shortcut.CloseOverlay"] = "Close overlay  /  go to Dashboard",
            ["Shortcut.PrivacyTip"] = "Toggle privacy mode (Ctrl+I)",
            ["Shortcut.ShortcutsTip"] = "Keyboard shortcuts (F1)",
            ["Cat.Food"] = "Food",
            ["Cat.Housing"] = "Housing",
            ["Cat.Transport"] = "Transport",
            ["Cat.Health"] = "Health",
            ["Cat.Entertainment"] = "Entertainment",
            ["Cat.Clothing"] = "Clothing",
            ["Cat.Education"] = "Education",
            ["Cat.Travel"] = "Travel",
            ["Cat.Bills"] = "Bills",
            ["Cat.Other"] = "Other",
            ["Goal.Achievable"] = "Goal achievable: {0}",
            ["Goal.AlreadyAchieved"] = "✅ Goal already achieved!",
            ["Goal.StartSaving"] = "Start saving to see a projection.",
            ["Goal.NoSavingsData"] = "No savings data yet.",
            ["Goal.CurrentPace"] = "At current pace: ~{0} month(s) – {1}",
            ["Goal.ExtraSavings"] = "💡 +{0} {1}/month → {2}{3}",
            ["Goal.MonthsSooner"] = ", {0} month(s) sooner 🚀",
            ["Goal.InsufficientTip1"] = "The prediction algorithm needs positive savings data from at least 3 recent months.",
            ["Goal.InsufficientTip2"] = "Months with positive savings detected: {0}/3.",
            ["Goal.InsufficientTip3"] = "Keep recording income and expense transactions to unlock this feature.",
            ["Goal.PrivacyProgress"] = "• • • / • • •",
            ["Tx.DataGridDate"] = "Date",
            ["Tx.DataGridType"] = "Type",
            ["Tx.DataGridCategory"] = "Category",
            ["Tx.DataGridNote"] = "Note",
            ["Tx.DataGridAmount"] = "Amount",
            ["Tx.DataGridDay"] = "Day",
            ["Label.FilterAll"] = "All",
            ["Settings.BackupRunDesc"] = "Export Backup saves an encrypted copy of your database. Import Backup restores all data from a previous backup (current data will be replaced).",
            ["Settings.DangerRunDesc"] = "Permanently delete your account and all associated data (transactions, budgets, goals, recurring transactions). This action cannot be undone.",
            ["Budget.DepositTip"] = "Deposit funds into this budget",
            ["Budget.DescTip"] = "e.g. Turkey, Poland – allows multiple budgets per category",
            ["Tray.CloseTitle"]   = "Close SmartAlloc",
            ["Tray.CloseMessage"] = "Minimize SmartAlloc to the system tray?\n\nYes – run in background (tray icon)\nNo – close the application completely",
            ["Tray.Running"]      = "SmartAlloc is running",
            ["Tray.RunningHint"]  = "Right-click the tray icon to open or exit.",
            ["Tray.WelcomeBack"]  = "Welcome back! 👋",
        },
        ["pl"] = new()
        {
            ["Nav.Dashboard"] = "Panel główny",
            ["Nav.Transactions"] = "Transakcje",
            ["Nav.Budgets"] = "Budżety",
            ["Nav.Goals"] = "Cele",
            ["Nav.Statistics"] = "Statystyki",
            ["Nav.Calendar"] = "Kalendarz",
            ["Nav.PdfReport"] = "Raport PDF",
            ["Nav.Settings"] = "Ustawienia",
            ["Nav.LogOut"] = "Wyloguj",
            ["Nav.Menu"] = "MENU",
            ["Title.Dashboard"] = "Panel główny",
            ["Title.DashboardSub"] = "Przegląd finansowy",
            ["Title.Transactions"] = "Transakcje",
            ["Title.TransactionsSub"] = "Zarządzaj przychodami i wydatkami",
            ["Title.Budgets"] = "Budżety",
            ["Title.BudgetsSub"] = "Kontroluj miesięczne limity wydatków",
            ["Title.Goals"] = "Cele oszczędnościowe",
            ["Title.GoalsSub"] = "Śledź postęp i prognozuj datę osiągnięcia celu",
            ["Title.Statistics"] = "Statystyki",
            ["Title.StatisticsSub"] = "Analizuj trendy wydatków",
            ["Title.Calendar"] = "Kalendarz płatności",
            ["Title.CalendarSub"] = "Przeglądaj i ustawiaj przypomnienia o płatnościach cyklicznych",
            ["Title.Settings"] = "Ustawienia",
            ["Title.SettingsSub"] = "Bezpieczeństwo i konfiguracja",
            ["Label.Balance"] = "Saldo",
            ["Label.Income"] = "Przychody",
            ["Label.Expenses"] = "Wydatki",
            ["Label.Savings"] = "Oszczędności",
            ["Label.Amount"] = "Kwota",
            ["Label.Date"] = "Data",
            ["Label.Category"] = "Kategoria",
            ["Label.Note"] = "Notatka",
            ["Label.Type"] = "Typ",
            ["Label.Colour"] = "Kolor",
            ["Label.Search"] = "Szukaj",
            ["Label.Period"] = "Okres",
            ["Label.Remaining"] = "Pozostało: ",
            ["Label.Description"] = "Opis (opcjonalnie)",
            ["Label.GoalName"] = "Nazwa celu",
            ["Label.Icon"] = "Ikona",
            ["Label.Language"] = "Język",
            ["Btn.AddTransaction"] = "Dodaj transakcję",
            ["Btn.SaveBudget"] = "Zapisz budżet",
            ["Btn.CreateGoal"] = "✅ Utwórz cel",
            ["Btn.Deposit"] = "💰 Wpłata",
            ["Btn.Delete"] = "Usuń",
            ["Btn.Save"] = "Zapisz",
            ["Btn.Cancel"] = "Anuluj",
            ["Btn.SaveNewPin"] = "Zapisz nowy PIN",
            ["Btn.ExportBackup"] = "📤  Eksport kopii",
            ["Btn.ImportBackup"] = "📥  Import kopii",
            ["Btn.DeleteAccount"] = "Usuń konto",
            ["Btn.SaveRecurring"] = "🔁 Zapisz cykliczne",
            ["Btn.AddQuickTx"] = "➕ Dodaj transakcję",
            ["Section.NewBudget"] = "➕ Nowy budżet:",
            ["Section.NewGoal"] = "🎯 Nowy cel oszczędnościowy",
            ["Section.NewTx"] = "➕ Nowa transakcja",
            ["Section.Filters"] = "🔍 Filtry",
            ["Section.ChangePin"] = "Zmień PIN",
            ["Section.AutoLock"] = "Automatyczna blokada",
            ["Section.Backup"] = "Kopia zapasowa",
            ["Section.Shortcuts"] = "Skróty klawiszowe",
            ["Section.DangerZone"] = "Strefa niebezpieczna",
            ["Section.Reminders"] = "🔔 Przypomnienia",
            ["Section.AllRecurring"] = "WSZYSTKIE PŁATNOŚCI CYKLICZNE",
            ["Section.AddRecurring"] = "🔁 Dodaj płatność cykliczną",
            ["Tx.Expense"] = "Wydatek",
            ["Tx.Income"] = "Przychód",
            ["Pin.CurrentPin"] = "Aktualny PIN",
            ["Pin.NewPin"] = "Nowy PIN",
            ["Pin.ConfirmPin"] = "Potwierdź nowy PIN",
            ["Settings.AutoLockDesc"] = "Zablokuj ekran po okresie bezczynności.",
            ["Settings.BackupDesc"] = "Eksport kopii zapasowej zapisuje zaszyfrowaną kopię bazy danych. Import przywraca dane z poprzedniej kopii (aktualne dane zostaną zastąpione).",
            ["Settings.DangerDesc"] = "Trwałe usunięcie konta i wszystkich powiązanych danych (transakcje, budżety, cele, płatności cykliczne). Tej operacji nie można cofnąć.",
            ["App.Title"] = "SmartAlloc",
            ["App.Subtitle"] = "Planowanie finansów",
            ["App.Version"] = "SmartAlloc v1.0",
            ["App.Encryption"] = "Dane zaszyfrowane AES-256",
            ["Theme.Light"] = "Tryb jasny",
            ["Theme.Dark"] = "Tryb ciemny",
            ["Calendar.RemindMe"] = "Przypomnij mi",
            ["Calendar.SaveReminder"] = "💾 Zapisz przypomnienie",
            ["Calendar.ClickDay"] = "Kliknij dzień z płatnością, aby ustawić przypomnienie.",
            ["Calendar.NameCategory"] = "Nazwa / Kategoria",
            ["Calendar.DayOfMonth"] = "Dzień miesiąca (1–28)",
            ["WhatIf.Prefix"] = "🔮 Co gdyby: dodatkowe oszczędności +",
            ["WhatIf.PerMonth"] = "/miesiąc",
            ["Label.DisplayCurrency"] = "Waluta wyświetlana",
            ["Label.DisplayCurrencyHint"] = "Waluta globalna jest również na pasku bocznym.",
            ["Btn.RefreshRates"] = "🔄 Odśwież kursy",
            ["Section.ExpenseBreakdown"] = "Struktura wydatków",
            ["Label.CurrentMonth"] = "Bieżący miesiąc  ·  ",
            ["Section.BalanceHistory"] = "Historia salda",
            ["Label.Last6Months"] = "Ostatnie 6 miesięcy",
            ["Section.TransactionList"] = "📋 Lista transakcji",
            ["Btn.DeleteSelected"] = "🗑 Usuń zaznaczone",
            ["Label.DayRange"] = "Dzień (1-28)",
            ["Btn.Add"] = "Dodaj",
            ["Section.RecurringTx"] = "🔁 Transakcje cykliczne",
            ["Tx.ExpenseRadio"] = "📉 Wydatek",
            ["Tx.IncomeRadio"] = "📈 Przychód",
            ["Label.TargetAmount"] = "Kwota docelowa",
            ["Label.InitialAmount"] = "Kwota początkowa",
            ["Btn.Back"] = "← Wróć",
            ["Label.InsufficientData"] = "ℹ️ Niewystarczające dane",
            ["Label.NoGoals"] = "Brak celów",
            ["Label.GoalCount"] = "cel(e/ów)",
            ["Title.AdvancedStats"] = "Zaawansowane statystyki",
            ["Title.AdvancedStatsSub"] = "Szczegółowa analiza wzorców wydatków i przychodów",
            ["Label.AvgDailyExpense"] = "📉 Śr. dzienny wydatek",
            ["Label.AvgDailyIncome"] = "📈 Śr. dzienny przychód",
            ["Label.SavingsRate"] = "💾 Stopa oszczędności",
            ["Label.BiggestExpense"] = "🔥 Największy wydatek",
            ["Section.TopExpense"] = "🏆 Największe kategorie wydatków (bieżący miesiąc)",
            ["Section.IncomeVsExpense"] = "📊 Przychody vs Wydatki (6 miesięcy)",
            ["Section.ExpenseTrend"] = "📈 Trend wydatków (12 miesięcy)",
            ["Section.LanguageDesc"] = "Wybierz język interfejsu. Aplikacja zaktualizuje się natychmiast.",
            ["Shortcut.Title"] = "Skróty klawiszowe",
            ["Shortcut.F1Hint"] = "  — naciśnij F1 aby otworzyć nakładkę",
            ["Shortcut.CloseHint"] = "  — naciśnij F1 lub Esc aby zamknąć",
            ["Shortcut.Navigation"] = "NAWIGACJA",
            ["Shortcut.Actions"] = "AKCJE",
            ["Shortcut.General"] = "OGÓLNE",
            ["Shortcut.NavPages"] = "Panel główny, Transakcje, Budżety, Cele, Statystyki, Ustawienia",
            ["Shortcut.NewTx"] = "Nowa transakcja (przejdź do Transakcji)",
            ["Shortcut.GenPdf"] = "Generuj raport PDF",
            ["Shortcut.ToggleTheme"] = "Przełącz jasny / ciemny motyw",
            ["Shortcut.LockScreen"] = "Zablokuj ekran",
            ["Shortcut.Minimize"] = "Minimalizuj okno",
            ["Shortcut.ToggleOverlay"] = "Pokaż / ukryj nakładkę skrótów",
            ["Shortcut.CloseOverlay"] = "Zamknij nakładkę / przejdź do Panelu",
            ["Shortcut.PrivacyTip"] = "Tryb prywatności (Ctrl+I)",
            ["Shortcut.ShortcutsTip"] = "Skróty klawiszowe (F1)",
            ["Cat.Food"] = "Jedzenie",
            ["Cat.Housing"] = "Mieszkanie",
            ["Cat.Transport"] = "Transport",
            ["Cat.Health"] = "Zdrowie",
            ["Cat.Entertainment"] = "Rozrywka",
            ["Cat.Clothing"] = "Odzież",
            ["Cat.Education"] = "Edukacja",
            ["Cat.Travel"] = "Podróże",
            ["Cat.Bills"] = "Rachunki",
            ["Cat.Other"] = "Inne",
            ["Goal.Achievable"] = "Cel osiągalny: {0}",
            ["Goal.AlreadyAchieved"] = "✅ Cel już osiągnięty!",
            ["Goal.StartSaving"] = "Zacznij oszczędzać, aby zobaczyć prognozę.",
            ["Goal.NoSavingsData"] = "Brak danych o oszczędnościach.",
            ["Goal.CurrentPace"] = "Przy obecnym tempie: ~{0} miesiąc(e/ów) – {1}",
            ["Goal.ExtraSavings"] = "💡 +{0} {1}/mies. → {2}{3}",
            ["Goal.MonthsSooner"] = ", {0} miesiąc(e/ów) szybciej 🚀",
            ["Goal.InsufficientTip1"] = "Algorytm prognozowania potrzebuje danych o pozytywnych oszczędnościach z co najmniej 3 ostatnich miesięcy.",
            ["Goal.InsufficientTip2"] = "Miesiące z pozytywnymi oszczędnościami: {0}/3.",
            ["Goal.InsufficientTip3"] = "Kontynuuj rejestrowanie transakcji przychodów i wydatków, aby odblokować tę funkcję.",
            ["Goal.PrivacyProgress"] = "• • • / • • •",
            ["Tx.DataGridDate"] = "Data",
            ["Tx.DataGridType"] = "Typ",
            ["Tx.DataGridCategory"] = "Kategoria",
            ["Tx.DataGridNote"] = "Notatka",
            ["Tx.DataGridAmount"] = "Kwota",
            ["Tx.DataGridDay"] = "Dzień",
            ["Label.FilterAll"] = "Wszystko",
            ["Settings.BackupRunDesc"] = "Eksport kopii zapisuje zaszyfrowaną kopię bazy danych. Import przywraca dane z poprzedniej kopii (aktualne dane zostaną zastąpione).",
            ["Settings.DangerRunDesc"] = "Trwałe usunięcie konta i wszystkich powiązanych danych (transakcje, budżety, cele, płatności cykliczne). Tej operacji nie można cofnąć.",
            ["Budget.DepositTip"] = "Wpłać środki do tego budżetu",
            ["Budget.DescTip"] = "np. Turcja, Polska – pozwala na kilka budżetów na kategorię",
            ["Tray.CloseTitle"]   = "Zamknij SmartAlloc",
            ["Tray.CloseMessage"] = "Zminimalizować SmartAlloc do zasobnika systemowego?\n\nTak – działaj w tle (ikona w zasobniku)\nNie – zamknij aplikację całkowicie",
            ["Tray.Running"]      = "SmartAlloc działa w tle",
            ["Tray.RunningHint"]  = "Kliknij prawym przyciskiem ikonę zasobnika, aby otworzyć lub zamknąć.",
            ["Tray.WelcomeBack"]  = "Witaj z powrotem! 👋",
        },
        ["de"] = new()
        {
            ["Nav.Dashboard"] = "Übersicht",
            ["Nav.Transactions"] = "Transaktionen",
            ["Nav.Budgets"] = "Budgets",
            ["Nav.Goals"] = "Ziele",
            ["Nav.Statistics"] = "Statistiken",
            ["Nav.Calendar"] = "Kalender",
            ["Nav.PdfReport"] = "PDF-Bericht",
            ["Nav.Settings"] = "Einstellungen",
            ["Nav.LogOut"] = "Abmelden",
            ["Nav.Menu"] = "MENÜ",
            ["Title.Dashboard"] = "Übersicht",
            ["Title.DashboardSub"] = "Ihr finanzieller Überblick",
            ["Title.Transactions"] = "Transaktionen",
            ["Title.TransactionsSub"] = "Verwalten Sie Ihre Einnahmen und Ausgaben",
            ["Title.Budgets"] = "Budgets",
            ["Title.BudgetsSub"] = "Kontrollieren Sie Ihre monatlichen Ausgabenlimits",
            ["Title.Goals"] = "Sparziele",
            ["Title.GoalsSub"] = "Verfolgen Sie den Fortschritt und prognostizieren Sie das Zielerreichungsdatum",
            ["Title.Statistics"] = "Statistiken",
            ["Title.StatisticsSub"] = "Analysieren Sie Ihre Ausgabentrends",
            ["Title.Calendar"] = "Zahlungskalender",
            ["Title.CalendarSub"] = "Erinnerungen für wiederkehrende Zahlungen anzeigen und festlegen",
            ["Title.Settings"] = "Einstellungen",
            ["Title.SettingsSub"] = "Sicherheit und Konfiguration",
            ["Label.Balance"] = "Saldo",
            ["Label.Income"] = "Einnahmen",
            ["Label.Expenses"] = "Ausgaben",
            ["Label.Savings"] = "Ersparnisse",
            ["Label.Amount"] = "Betrag",
            ["Label.Date"] = "Datum",
            ["Label.Category"] = "Kategorie",
            ["Label.Note"] = "Notiz",
            ["Label.Type"] = "Typ",
            ["Label.Colour"] = "Farbe",
            ["Label.Search"] = "Suche",
            ["Label.Period"] = "Zeitraum",
            ["Label.Remaining"] = "Verbleibend: ",
            ["Label.Description"] = "Beschreibung (optional)",
            ["Label.GoalName"] = "Zielname",
            ["Label.Icon"] = "Symbol",
            ["Label.Language"] = "Sprache",
            ["Btn.AddTransaction"] = "Transaktion hinzufügen",
            ["Btn.SaveBudget"] = "Budget speichern",
            ["Btn.CreateGoal"] = "✅ Ziel erstellen",
            ["Btn.Deposit"] = "💰 Einzahlung",
            ["Btn.Delete"] = "Löschen",
            ["Btn.Save"] = "Speichern",
            ["Btn.Cancel"] = "Abbrechen",
            ["Btn.SaveNewPin"] = "Neue PIN speichern",
            ["Btn.ExportBackup"] = "📤  Backup exportieren",
            ["Btn.ImportBackup"] = "📥  Backup importieren",
            ["Btn.DeleteAccount"] = "Konto löschen",
            ["Btn.SaveRecurring"] = "🔁 Wiederkehrend speichern",
            ["Btn.AddQuickTx"] = "➕ Transaktion hinzufügen",
            ["Section.NewBudget"] = "➕ Neues Budget:",
            ["Section.NewGoal"] = "🎯 Neues Sparziel",
            ["Section.NewTx"] = "➕ Neue Transaktion",
            ["Section.Filters"] = "🔍 Filter",
            ["Section.ChangePin"] = "PIN ändern",
            ["Section.AutoLock"] = "Automatische Sperre",
            ["Section.Backup"] = "Sicherung & Wiederherstellung",
            ["Section.Shortcuts"] = "Tastenkombinationen",
            ["Section.DangerZone"] = "Gefahrenzone",
            ["Tx.Expense"] = "Ausgabe",
            ["Tx.Income"] = "Einnahme",
        },
        ["es"] = new()
        {
            ["Nav.Dashboard"] = "Panel",
            ["Nav.Transactions"] = "Transacciones",
            ["Nav.Budgets"] = "Presupuestos",
            ["Nav.Goals"] = "Metas",
            ["Nav.Statistics"] = "Estadísticas",
            ["Nav.Calendar"] = "Calendario",
            ["Nav.PdfReport"] = "Informe PDF",
            ["Nav.Settings"] = "Ajustes",
            ["Nav.LogOut"] = "Cerrar sesión",
            ["Nav.Menu"] = "MENÚ",
            ["Title.Dashboard"] = "Panel",
            ["Title.DashboardSub"] = "Tu resumen financiero",
            ["Title.Transactions"] = "Transacciones",
            ["Title.TransactionsSub"] = "Gestiona tus ingresos y gastos",
            ["Title.Budgets"] = "Presupuestos",
            ["Title.BudgetsSub"] = "Controla tus límites de gasto mensuales",
            ["Title.Goals"] = "Metas de ahorro",
            ["Title.GoalsSub"] = "Sigue el progreso y predice la fecha de logro",
            ["Title.Statistics"] = "Estadísticas",
            ["Title.StatisticsSub"] = "Analiza tus tendencias de gasto",
            ["Title.Calendar"] = "Calendario de pagos",
            ["Title.CalendarSub"] = "Ver y configurar recordatorios de pagos recurrentes",
            ["Title.Settings"] = "Ajustes",
            ["Title.SettingsSub"] = "Seguridad y configuración",
            ["Label.Balance"] = "Saldo",
            ["Label.Income"] = "Ingresos",
            ["Label.Expenses"] = "Gastos",
            ["Label.Savings"] = "Ahorros",
            ["Label.Amount"] = "Monto",
            ["Label.Date"] = "Fecha",
            ["Label.Category"] = "Categoría",
            ["Label.Note"] = "Nota",
            ["Label.Type"] = "Tipo",
            ["Label.Colour"] = "Color",
            ["Label.Search"] = "Buscar",
            ["Label.Period"] = "Período",
            ["Label.Remaining"] = "Restante: ",
            ["Label.Description"] = "Descripción (opcional)",
            ["Label.GoalName"] = "Nombre de la meta",
            ["Label.Icon"] = "Ícono",
            ["Label.Language"] = "Idioma",
            ["Btn.AddTransaction"] = "Agregar transacción",
            ["Btn.SaveBudget"] = "Guardar presupuesto",
            ["Btn.CreateGoal"] = "✅ Crear meta",
            ["Btn.Deposit"] = "💰 Depósito",
            ["Btn.Delete"] = "Eliminar",
            ["Btn.Save"] = "Guardar",
            ["Btn.Cancel"] = "Cancelar",
            ["Tx.Expense"] = "Gasto",
            ["Tx.Income"] = "Ingreso",
        },
        ["fr"] = new()
        {
            ["Nav.Dashboard"] = "Tableau de bord",
            ["Nav.Transactions"] = "Transactions",
            ["Nav.Budgets"] = "Budgets",
            ["Nav.Goals"] = "Objectifs",
            ["Nav.Statistics"] = "Statistiques",
            ["Nav.Calendar"] = "Calendrier",
            ["Nav.PdfReport"] = "Rapport PDF",
            ["Nav.Settings"] = "Paramètres",
            ["Nav.LogOut"] = "Déconnexion",
            ["Nav.Menu"] = "MENU",
            ["Title.Dashboard"] = "Tableau de bord",
            ["Title.DashboardSub"] = "Votre aperçu financier",
            ["Title.Transactions"] = "Transactions",
            ["Title.TransactionsSub"] = "Gérez vos revenus et dépenses",
            ["Title.Budgets"] = "Budgets",
            ["Title.BudgetsSub"] = "Contrôlez vos limites de dépenses mensuelles",
            ["Title.Goals"] = "Objectifs d'épargne",
            ["Title.GoalsSub"] = "Suivez les progrès et prédisez la date d'atteinte",
            ["Title.Statistics"] = "Statistiques",
            ["Title.StatisticsSub"] = "Analysez vos tendances de dépenses",
            ["Title.Calendar"] = "Calendrier des paiements",
            ["Title.CalendarSub"] = "Afficher et définir les rappels de paiements récurrents",
            ["Title.Settings"] = "Paramètres",
            ["Title.SettingsSub"] = "Sécurité et configuration",
            ["Label.Balance"] = "Solde",
            ["Label.Income"] = "Revenus",
            ["Label.Expenses"] = "Dépenses",
            ["Label.Savings"] = "Épargne",
            ["Label.Amount"] = "Montant",
            ["Label.Date"] = "Date",
            ["Label.Category"] = "Catégorie",
            ["Label.Note"] = "Note",
            ["Label.Type"] = "Type",
            ["Label.Colour"] = "Couleur",
            ["Label.Search"] = "Rechercher",
            ["Label.Period"] = "Période",
            ["Label.Remaining"] = "Restant : ",
            ["Label.Description"] = "Description (facultatif)",
            ["Label.GoalName"] = "Nom de l'objectif",
            ["Label.Icon"] = "Icône",
            ["Label.Language"] = "Langue",
            ["Btn.AddTransaction"] = "Ajouter une transaction",
            ["Btn.SaveBudget"] = "Enregistrer le budget",
            ["Btn.CreateGoal"] = "✅ Créer un objectif",
            ["Btn.Deposit"] = "💰 Dépôt",
            ["Btn.Delete"] = "Supprimer",
            ["Btn.Save"] = "Enregistrer",
            ["Btn.Cancel"] = "Annuler",
            ["Tx.Expense"] = "Dépense",
            ["Tx.Income"] = "Revenu",
        },
        ["pt"] = new()
        {
            ["Nav.Dashboard"] = "Painel",
            ["Nav.Transactions"] = "Transações",
            ["Nav.Budgets"] = "Orçamentos",
            ["Nav.Goals"] = "Metas",
            ["Nav.Statistics"] = "Estatísticas",
            ["Nav.Calendar"] = "Calendário",
            ["Nav.PdfReport"] = "Relatório PDF",
            ["Nav.Settings"] = "Configurações",
            ["Nav.LogOut"] = "Sair",
            ["Nav.Menu"] = "MENU",
            ["Title.Dashboard"] = "Painel",
            ["Title.DashboardSub"] = "Sua visão financeira",
            ["Title.Transactions"] = "Transações",
            ["Title.TransactionsSub"] = "Gerencie suas receitas e despesas",
            ["Title.Budgets"] = "Orçamentos",
            ["Title.BudgetsSub"] = "Controle seus limites de gastos mensais",
            ["Title.Goals"] = "Metas de poupança",
            ["Title.GoalsSub"] = "Acompanhe o progresso e preveja a data de conquista",
            ["Title.Statistics"] = "Estatísticas",
            ["Title.StatisticsSub"] = "Analise suas tendências de gastos",
            ["Title.Settings"] = "Configurações",
            ["Title.SettingsSub"] = "Segurança e configuração",
            ["Label.Balance"] = "Saldo",
            ["Label.Income"] = "Receita",
            ["Label.Expenses"] = "Despesas",
            ["Label.Amount"] = "Valor",
            ["Label.Category"] = "Categoria",
            ["Label.Note"] = "Nota",
            ["Label.Language"] = "Idioma",
            ["Btn.AddTransaction"] = "Adicionar transação",
            ["Btn.SaveBudget"] = "Salvar orçamento",
            ["Btn.CreateGoal"] = "✅ Criar meta",
            ["Btn.Deposit"] = "💰 Depósito",
            ["Tx.Expense"] = "Despesa",
            ["Tx.Income"] = "Receita",
        },
        ["ru"] = new()
        {
            ["Nav.Dashboard"] = "Обзор",
            ["Nav.Transactions"] = "Транзакции",
            ["Nav.Budgets"] = "Бюджеты",
            ["Nav.Goals"] = "Цели",
            ["Nav.Statistics"] = "Статистика",
            ["Nav.Calendar"] = "Календарь",
            ["Nav.PdfReport"] = "PDF отчёт",
            ["Nav.Settings"] = "Настройки",
            ["Nav.LogOut"] = "Выход",
            ["Nav.Menu"] = "МЕНЮ",
            ["Title.Dashboard"] = "Обзор",
            ["Title.DashboardSub"] = "Ваш финансовый обзор",
            ["Title.Transactions"] = "Транзакции",
            ["Title.TransactionsSub"] = "Управляйте доходами и расходами",
            ["Title.Budgets"] = "Бюджеты",
            ["Title.BudgetsSub"] = "Контролируйте месячные лимиты расходов",
            ["Title.Goals"] = "Цели сбережений",
            ["Title.GoalsSub"] = "Отслеживайте прогресс и прогнозируйте дату достижения",
            ["Title.Statistics"] = "Статистика",
            ["Title.StatisticsSub"] = "Анализируйте тенденции расходов",
            ["Title.Settings"] = "Настройки",
            ["Title.SettingsSub"] = "Безопасность и конфигурация",
            ["Label.Balance"] = "Баланс",
            ["Label.Income"] = "Доходы",
            ["Label.Expenses"] = "Расходы",
            ["Label.Amount"] = "Сумма",
            ["Label.Category"] = "Категория",
            ["Label.Note"] = "Заметка",
            ["Label.Language"] = "Язык",
            ["Btn.AddTransaction"] = "Добавить транзакцию",
            ["Btn.SaveBudget"] = "Сохранить бюджет",
            ["Btn.CreateGoal"] = "✅ Создать цель",
            ["Btn.Deposit"] = "💰 Вклад",
            ["Tx.Expense"] = "Расход",
            ["Tx.Income"] = "Доход",
        },
        ["zh"] = new()
        {
            ["Nav.Dashboard"] = "仪表盘",
            ["Nav.Transactions"] = "交易",
            ["Nav.Budgets"] = "预算",
            ["Nav.Goals"] = "目标",
            ["Nav.Statistics"] = "统计",
            ["Nav.Calendar"] = "日历",
            ["Nav.PdfReport"] = "PDF报告",
            ["Nav.Settings"] = "设置",
            ["Nav.LogOut"] = "退出",
            ["Nav.Menu"] = "菜单",
            ["Title.Dashboard"] = "仪表盘",
            ["Title.DashboardSub"] = "您的财务概况",
            ["Title.Transactions"] = "交易",
            ["Title.TransactionsSub"] = "管理您的收入和支出",
            ["Title.Budgets"] = "预算",
            ["Title.BudgetsSub"] = "控制每月支出限额",
            ["Title.Goals"] = "储蓄目标",
            ["Title.GoalsSub"] = "跟踪进度并预测目标达成日期",
            ["Title.Statistics"] = "统计",
            ["Title.StatisticsSub"] = "分析支出趋势",
            ["Title.Settings"] = "设置",
            ["Title.SettingsSub"] = "安全和配置",
            ["Label.Balance"] = "余额",
            ["Label.Income"] = "收入",
            ["Label.Expenses"] = "支出",
            ["Label.Amount"] = "金额",
            ["Label.Category"] = "分类",
            ["Label.Note"] = "备注",
            ["Label.Language"] = "语言",
            ["Btn.AddTransaction"] = "添加交易",
            ["Btn.SaveBudget"] = "保存预算",
            ["Btn.CreateGoal"] = "✅ 创建目标",
            ["Btn.Deposit"] = "💰 存款",
            ["Tx.Expense"] = "支出",
            ["Tx.Income"] = "收入",
        },
        ["ja"] = new()
        {
            ["Nav.Dashboard"] = "ダッシュボード",
            ["Nav.Transactions"] = "取引",
            ["Nav.Budgets"] = "予算",
            ["Nav.Goals"] = "目標",
            ["Nav.Statistics"] = "統計",
            ["Nav.Calendar"] = "カレンダー",
            ["Nav.PdfReport"] = "PDFレポート",
            ["Nav.Settings"] = "設定",
            ["Nav.LogOut"] = "ログアウト",
            ["Nav.Menu"] = "メニュー",
            ["Title.Dashboard"] = "ダッシュボード",
            ["Title.DashboardSub"] = "財務概要",
            ["Title.Transactions"] = "取引",
            ["Title.TransactionsSub"] = "収入と支出を管理",
            ["Title.Budgets"] = "予算",
            ["Title.BudgetsSub"] = "月間支出制限を管理",
            ["Title.Goals"] = "貯蓄目標",
            ["Title.GoalsSub"] = "進捗を追跡し目標達成日を予測",
            ["Title.Statistics"] = "統計",
            ["Title.StatisticsSub"] = "支出傾向を分析",
            ["Title.Settings"] = "設定",
            ["Title.SettingsSub"] = "セキュリティと設定",
            ["Label.Balance"] = "残高",
            ["Label.Income"] = "収入",
            ["Label.Expenses"] = "支出",
            ["Label.Amount"] = "金額",
            ["Label.Category"] = "カテゴリ",
            ["Label.Note"] = "メモ",
            ["Label.Language"] = "言語",
            ["Btn.AddTransaction"] = "取引を追加",
            ["Btn.SaveBudget"] = "予算を保存",
            ["Btn.CreateGoal"] = "✅ 目標を作成",
            ["Btn.Deposit"] = "💰 入金",
            ["Tx.Expense"] = "支出",
            ["Tx.Income"] = "収入",
        },
        ["ar"] = new()
        {
            ["Nav.Dashboard"] = "لوحة المعلومات",
            ["Nav.Transactions"] = "المعاملات",
            ["Nav.Budgets"] = "الميزانيات",
            ["Nav.Goals"] = "الأهداف",
            ["Nav.Statistics"] = "الإحصائيات",
            ["Nav.Calendar"] = "التقويم",
            ["Nav.PdfReport"] = "تقرير PDF",
            ["Nav.Settings"] = "الإعدادات",
            ["Nav.LogOut"] = "تسجيل الخروج",
            ["Nav.Menu"] = "القائمة",
            ["Title.Dashboard"] = "لوحة المعلومات",
            ["Title.DashboardSub"] = "نظرة عامة على أموالك",
            ["Title.Settings"] = "الإعدادات",
            ["Title.SettingsSub"] = "الأمان والتكوين",
            ["Label.Balance"] = "الرصيد",
            ["Label.Income"] = "الدخل",
            ["Label.Expenses"] = "المصروفات",
            ["Label.Amount"] = "المبلغ",
            ["Label.Category"] = "الفئة",
            ["Label.Note"] = "ملاحظة",
            ["Label.Language"] = "اللغة",
            ["Tx.Expense"] = "مصروف",
            ["Tx.Income"] = "دخل",
        },
        ["hi"] = new()
        {
            ["Nav.Dashboard"] = "डैशबोर्ड",
            ["Nav.Transactions"] = "लेन-देन",
            ["Nav.Budgets"] = "बजट",
            ["Nav.Goals"] = "लक्ष्य",
            ["Nav.Statistics"] = "आँकड़े",
            ["Nav.Calendar"] = "कैलेंडर",
            ["Nav.PdfReport"] = "PDF रिपोर्ट",
            ["Nav.Settings"] = "सेटिंग्स",
            ["Nav.LogOut"] = "लॉग आउट",
            ["Nav.Menu"] = "मेन्यू",
            ["Title.Dashboard"] = "डैशबोर्ड",
            ["Title.DashboardSub"] = "आपका वित्तीय अवलोकन",
            ["Title.Settings"] = "सेटिंग्स",
            ["Title.SettingsSub"] = "सुरक्षा और कॉन्फ़िगरेशन",
            ["Label.Balance"] = "शेष",
            ["Label.Income"] = "आय",
            ["Label.Expenses"] = "व्यय",
            ["Label.Amount"] = "राशि",
            ["Label.Category"] = "श्रेणी",
            ["Label.Note"] = "नोट",
            ["Label.Language"] = "भाषा",
            ["Tx.Expense"] = "व्यय",
            ["Tx.Income"] = "आय",
        },
    };

    public string Get(string key)
    {
        if (Translations.TryGetValue(_currentLanguage, out var dict) && dict.TryGetValue(key, out var val))
            return val;
        if (Translations.TryGetValue("en", out var en) && en.TryGetValue(key, out var fallback))
            return fallback;
        return key;
    }

    public void SetLanguage(string code, Data.DatabaseContext? db = null)
    {
        if (!Translations.ContainsKey(code)) return;
        _currentLanguage = code;
        db?.SetSetting("Language", code);
        LanguageChanged?.Invoke();
    }

    public void LoadSaved(Data.DatabaseContext db)
    {
        var saved = db.GetSetting("Language");
        if (!string.IsNullOrEmpty(saved) && Translations.ContainsKey(saved))
            _currentLanguage = saved;
    }

    private static readonly Dictionary<string, string> CategoryKeyMap = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Food"]          = "Cat.Food",
        ["Housing"]       = "Cat.Housing",
        ["Transport"]     = "Cat.Transport",
        ["Health"]        = "Cat.Health",
        ["Entertainment"] = "Cat.Entertainment",
        ["Clothing"]      = "Cat.Clothing",
        ["Education"]     = "Cat.Education",
        ["Travel"]        = "Cat.Travel",
        ["Bills"]         = "Cat.Bills",
        ["Other"]         = "Cat.Other",
    };

    public string TranslateCategory(string dbName)
    {
        if (string.IsNullOrEmpty(dbName)) return dbName;
        var spaceIdx = dbName.IndexOf(' ');
        if (spaceIdx < 0) return dbName;
        string emoji = dbName[..spaceIdx];
        string word  = dbName[(spaceIdx + 1)..].Trim();
        if (CategoryKeyMap.TryGetValue(word, out var key))
            return $"{emoji} {Get(key)}";
        return dbName;
    }
}

public record LanguageOption(string Code, string DisplayName)
{
    public override string ToString() => DisplayName;
}
